### ISSUE TITLE
Where to store the token in an Electron App

### ISSUE THREAD

**Issue by Game-Unity** [ideologix/dlm-php#1]
What is a good location for storing the activation token inside an Electron app? Also, does the toke include the device id or something?  Or could I just copy the token and make have the premium app on any device?

**Comment by gdarko** [comment]
HI @Game-Unity  - Sorry for my late reply. 

1. I haven't used Electron, but you can store it in any storage that is not temporary or random access memory. Something that is permanent. Do you have access to the file system or some kind of database?
2. The activation token is unique identifier for each activation / device. When activating a license you can supply device Id in the meta_data array and later access it when validating the license activation token.
