### ISSUE TITLE
Where is autoload.php?

### ISSUE THREAD

**Issue by keneniah** [ideologix/dlm-php#2]
Hi,

I downloaded dlm-php from your master repository but I can't find a way to use it because there is no autoload.php file.
Can you please help me out on this?

Thank you very much.

Holger

**Comment by yonifre** [comment]
Same isso here, 
would love to know how can i install it without composer
Thank you,
Yoni.

**Comment by gdarko** [comment]
This can now be closed. The autoload.php was added, but at the time the issue was open it was not there.
